### ISSUE TITLE
Improve resource/variable naming and semantics

### ISSUE THREAD

**Issue by sshvetsov** [traveloka/terraform-aws-ecs-fargate-service#3]
### Resource Names / Definitions
1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L1
Personally, I'm not a big fan of having multiple resources share the same logical name. I find it confusing and less readable. Perhaps `ecs_service` or `ecs_svc` would be better logical name?

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L1-L29
If ECS service supports tags it should have them declared here as per our tagging conventions. If we do not yet have convention defined, @traveloka/techops should define tagging convention first.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L31
Similarly, `task_definition` or `task_def` seems like a better logical name to me.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L31-L46
If task definition supports tags it should have them declared here as per our tagging conventions. If we do not yet have convention defined, @traveloka/techops should define tagging convention first.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L62
I suggest simply naming this `log_group` since this module already represents service.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L62-L65
Log groups should have tags as per our resource tagging conventions. I also think name should be auto generated in accordance with our naming conventions. If log group naming convention specific to ECS service is not yet defined, it should be first defined by @traveloka/techops 

### Resource Properties
1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L3
I recommend simply using a variable here, instead of data source. This will allow end user to simply pass cluster ARN, instead of trying to figure out the cluster ARN from its name inside the module. IMHO it's less fragile, more future proof and makes no assumptions about environment this module will be deployed in.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L6
If you're going to hardcode FARGATE as  launch type, then module should be re-named to `terraform-aws-ecs-fargate-service`.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/main.tf#L37
I recommend just passing IAM Role ARN via variable. I think it is safer, and more future proof, instead of trying to guess ARN based on the Role name (e.g. IAM Roles might have a custom Path).

### Data sources
1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/data.tf#L3-L5
I think this can be removed based on my recommendations on cluster ARN above.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/data.tf#L7-L9
I think this can be removed based on my recommendations on execution role ARN above.

### Variable Names / Descriptions / Semantics
1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L1-L2
I suggest `Name of the ECS service. Note: this value will be also used to name resources`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L6-L7
I suggest renaming to `ecs_cluster_arn` or `ecs_fargate_cluster_arn` for better readability and change description to `ARN of the ECS Fargate cluster to launch service in`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L11-L12
I suggest description `Version of the Fargate platform to run the service on`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L17-L18
I suggest description `Number of tasks to run in the service`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L23-L24
I suggest name: `target_group_arn` and description `ARN of the ALB target group to associate with the service`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L28-L29
I suggest description `Name of the docker image that will be used by the task`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L33-L34
I suggest name `image_version` and description `Version/tag of the docker image to be used by the task`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L38-L39
I suggest name `container_name`, since there is not other container names in this module and description `Name to give to the container`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L44-L45
I suggest name `container_port` and description `Port for container to listen for incoming connections`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L50-L51
I suggest name `subnet_ids` to make it clearer that we expect a list of subnet IDs, and description `List of IDs of subnets to launch the service in`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L55-L56
I suggest name `security_group_ids` and description `List of IDs of security groups to associate with the service`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L60-L61
I suggest description `Whether or not to assign public IP address to the task ENI`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L66-L69
I suggest removing this variable and programmatically generating the log group name based on the service name using our naming conventions. If convention for ECS service log groups is not yet defined, @traveloka/techops should define it first.

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L71-L75
I suggest name `log_retention_in_days`, default of `14` as it is our current standard for app logs, and description `Number of days to retain service logs`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L83-L86
I suggest name `task_role_arn` and description `ARN of IAM role to be used by the task`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L89-L92
I suggest name `ecs_service_role_arn` or `fargate_service_role_arn` and description `ARN of IAM role to be used by Fargate to launch tasks`. BTW, the default value does not appear to follow our IAM role naming conventions, roles assumed by AWS services should have names like `ServiceRoleForEcs_task-execution`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L95-L96
I suggest name `environment_vars` and description `List of environment variables to pass to the task`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L101-L102
I suggest description `Number of cpu units to allocate for one task`

1. https://github.com/traveloka/terraform-aws-ecs-service/blob/80d886099bacacaa8afa4936244720e3d8509254/variables.tf#L107-L108
I suggest description `Amount of memory (in MiB) to allocate for one task`

**Comment by abihf** [comment]
### Resource Properties
> 2. If you're going to hardcode FARGATE as launch type, then module should be re-named to terraform-aws-ecs-fargate-service.

Because non fargate service require different set of variables, I'm thinking of renaming it to `terraform-aws-ecs-fargate-service`

### Variable Names / Descriptions / Semantics
> 8. I suggest name container_name, since there is not other container names in this module and description Name to give to the container 

We can add multiple container by overriding `container_definition_template`, so I think variable `main_container_name` still makes sense.

> 16. I suggest name ecs_service_role_arn or fargate_service_role_arn and description ARN of IAM role to be used by Fargate to launch tasks. BTW, the default value does not appear to follow our IAM role naming conventions, roles assumed by AWS services should have names like ServiceRoleForEcs_task-execution

I will delete the default value. And the role isn't used by ECS service, instead it's used by task to download image from ECR and read SSM, so I think it should be named `task_execution_role_arn`.

**Comment by abihf** [comment]
For logging name, I have proposal:
```tf
resource "aws_cloudwatch_log_group" "log_group" {
  name = 
"/tvlk/${var.cluster_role}-${var.application}/${var.service_name}/${var.container_name}"
}
```

Example: `/tvlk/fe-nodejs/webwww/main`

**Comment by sshvetsov** [comment]
> We can add multiple container by overriding `container_definition_template`, so I think variable `main_container_name` still makes sense.

In that case `container_port` should be called `main_container_port`

> The role isn't used by ECS service, instead it's used by task to download image from ECR and read SSM, so I think it should be named task_execution_role_arn.

I don't think the Task itself will be the one downloading the container image, based on the [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html) it will be the Amazon ECS container agent. In that case, I suggest name `execution_role_arn` and description `ARN of IAM role to be used by container agent to pull container images, write logs, access ECS secrets and parameter store`.

**Comment by sshvetsov** [comment]
> For logging name, I have proposal:
> 
> ```terraform
> resource "aws_cloudwatch_log_group" "log_group" {
>   name = 
> "/tvlk/${var.cluster_role}-${var.application}/${var.service_name}/${var.container_name}"
> }
> ```
> 
> Example: `/tvlk/fe-nodejs/webwww/main`

If you're saying more than one container can be defined in the task definition, I think placing container name in the log group name is going to be redundant, since you are creating only one Log Group for the entire service. I think instead, the container name could be used as part of the log stream prefix, together with the version inside the task definition. Perhaps, something like this:
```json
"logConfiguration": {
      "logDriver": "awslogs",
      "options": {
        "awslogs-group": "${log_group}",
        "awslogs-region": "${aws_region}",
        "awslogs-stream-prefix": "${container_name}/${version}/"
      }
```
Which means the Log Group name should be something like this:

```
"/tvlk/${var.cluster_role}-${var.application}/${var.service_name}-RANDOM_ID"
```
